// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Summarizes user contact requests using AI.
 *
 * - summarizeContactRequest - A function that summarizes the contact request.
 * - SummarizeContactRequestInput - The input type for the summarizeContactRequest function.
 * - SummarizeContactRequestOutput - The return type for the summarizeContactRequest function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SummarizeContactRequestInputSchema = z.object({
  name: z.string().describe('The name of the user submitting the request.'),
  email: z.string().email().describe('The email address of the user.'),
  message: z.string().describe('The contact request message from the user.'),
});
export type SummarizeContactRequestInput = z.infer<typeof SummarizeContactRequestInputSchema>;

const SummarizeContactRequestOutputSchema = z.object({
  summary: z.string().describe('A concise summary of the contact request.'),
});
export type SummarizeContactRequestOutput = z.infer<typeof SummarizeContactRequestOutputSchema>;

export async function summarizeContactRequest(input: SummarizeContactRequestInput): Promise<SummarizeContactRequestOutput> {
  return summarizeContactRequestFlow(input);
}

const prompt = ai.definePrompt({
  name: 'summarizeContactRequestPrompt',
  input: {schema: SummarizeContactRequestInputSchema},
  output: {schema: SummarizeContactRequestOutputSchema},
  prompt: `You are an AI assistant tasked with summarizing user contact requests.

  Summarize the following contact request in a concise and informative manner.
  Include the key points and the user's main intention.

  User Name: {{{name}}}
  User Email: {{{email}}}
  Message: {{{message}}}
  \nSummary: `,
});

const summarizeContactRequestFlow = ai.defineFlow(
  {
    name: 'summarizeContactRequestFlow',
    inputSchema: SummarizeContactRequestInputSchema,
    outputSchema: SummarizeContactRequestOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
